version: '3'
services:
    portainer:
        container_name: portainer
        image: portainer/portainer:latest
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /opt/portainer:/data
        ports:
            - 9000:9000
